### ISSUE TITLE
Lab 2 【五、实验数据记录和处理】第三步勘误

### ISSUE THREAD

**Issue by JiepengLab** [lvmiao233/ZJU24CompNet#1]
![image](https://github.com/user-attachments/assets/ac2bfe9c-46bf-4aea-a723-742126e8ce2c)

应如截图参考中的`dir flash:`，而不应该是`show flash`（我在实验中尝试过`show flash`，并不成功）
输入命令`dir flash:`~`show flash`~ : 查看当前文件系统的内容，并将展示结果截图

**Comment by lvmiao233** [comment]
这一问题可能与思科不同设备对指令不同支持情况导致，已在Commit c7924e3a5c314f3fa1d797e5ae69e319a6ae6033补充dir flash命令，感谢你的反馈♥
