### ISSUE TITLE
Lab 4 静态路由配置 指令疑似笔误

### ISSUE THREAD

**Issue by ZhengliangDuanfang** [lvmiao233/ZJU24CompNet#2]
这里的疑似笔误出现在「四、操作方法与实验步骤」部分。

![屏幕截图 2024-10-31 141113](https://github.com/user-attachments/assets/92030030-ddbb-4870-a05c-87c355671813)

箭头指向处的两星号`*`似乎不是指令内容。另外，这里提到的参考文献似乎可以添加链接。

**Comment by lvmiao233** [comment]
该问题已在Commit f19de6b修复，感谢你的反馈❤！
